# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yFpc-U6nXEY9mvEs42dhNhPkpp3RzMB0
"""

print("Hello World")